### ISSUE TITLE
Trash

### ISSUE THREAD

**Issue by ghost** [TheFeministSoftwareFoundation/C-plus-Equality#14]
normal woman good

mega feminsist woman bad

fuck off retards

**Comment by ghost** [comment]
Feminism is something good imo.

**Comment by gamerboy80** [comment]
> 
> 
> Feminism is something good imo.

No.

**Comment by ghost** [comment]
Explain how so...

**Comment by solinym** [comment]
amen

**Comment by Stevontavius** [comment]
> Feminism is something good imo.

NO IT'S NOT
