### ISSUE TITLE
kinda missing the point, eh?

### ISSUE THREAD

**Issue by mnemocron** [TheFeministSoftwareFoundation/C-plus-Equality#8]
Feminists: There is a lack of women in MINT jobs. Also partly because this male dominated area tends to be over proportionally right leaning and misogynistic.

"TheFeministSoftwareFoundation": haha lul, let's make a repo to mock feminists, that will show them that there is no problem :^)

aka. owning libtards™ by proofing their point

**Comment by JacksonTravisRipper** [comment]
no1 cares tho

**Comment by ghost** [comment]
we're seriously lacking workforce in the industry, we're taking on anyone who can code, we don't care what genitalia they have or whether they look like chunk norris.

taking gender into the equation in the first place proved you are no more than a troll
